Draw instanced session2
facebook/igl pull request #124
Opened 2024-06-09 01:39 UTC by vinsentli

2024-06-09 21:22 UTC, corporateshark requested changes

2024-06-09 21:22 UTC, corporateshark commented on shell/renderSessions/DrawInstancedSession.cpp
> +            //method one：
Please remove unused code.

2024-06-09 21:22 UTC, corporateshark commented on shell/renderSessions/DrawInstancedSession.cpp
> +  // @fb-only
Remove internal markup.

2024-06-09 21:22 UTC, corporateshark commented on shell/renderSessions/DrawInstancedSession.cpp
> +            std::regex_replace(codeVS2.c_str(), std::regex("layout \\(location=0\\) out"), "out");
No need to use regexps for this. Use this instead (change to `const char*` where appropriate):
```
[[maybe_unused]] void stringReplaceAll(std::string& s,
                                       const std::string& searchString,
                                       const std::string& replaceString) {
  size_t pos = 0;
  while ((pos = s.find(searchString, pos)) != std::string::npos) {
    s.replace(pos, searchString.length(), replaceString);
  }
}
```
Please remove all `<regex>` usage.

2024-06-09 21:22 UTC, corporateshark commented on shell/renderSessions/DrawInstancedSession.h
> +// @fb-only
Remove internal markup in this new file.

2024-06-10 01:12 UTC, vinsentli commented
@corporateshark 
I have made the modifications according to your advice.

2024-06-10 01:17 UTC, corporateshark approved these changes
@vinsentli I will import this PR once https://github.com/facebook/igl/pull/121 is merged.

2024-06-10 03:50 UTC, corporateshark requested changes

2024-06-10 03:50 UTC, corporateshark commented on shell/renderSessions/DrawInstancedSession.cpp
> +  int16_t indexes[6] = {0, 1, 2, 3, 4, 5};
`const`

2024-06-10 03:50 UTC, corporateshark commented on shell/renderSessions/DrawInstancedSession.cpp
> +  commands->drawIndexed(PrimitiveType::Triangle, 6, 100);
This method is deprecated and will be removed. Use `drawIndexed(6, 100)`.

2024-06-13 04:54 UTC, corporateshark commented
@vinsentli please rebase onto the latest `main` branch.

2024-06-13 06:31 UTC, closed without merging

2024-06-13 06:55 UTC, vinsentli commented
> @vinsentli please rebase onto the latest `main` branch.

I rebase onto the latest `main` branch， noticed that there are quite a few exceptions.

So i create a new PR :  https://github.com/facebook/igl/pull/132