shell | Add DrawInstancedSession
facebook/igl pull request #132
Opened 2024-06-13 06:53 UTC by vinsentli

same with https://github.com/facebook/igl/pull/124

2024-06-13 07:02 UTC, corporateshark requested changes

2024-06-13 07:02 UTC, corporateshark commented on src/igl/opengl/RenderCommandEncoder.cpp
> -  IGL_ASSERT_MSG(baseInstance == 0, "Instancing is not implemented");
`baseInstance` should not be touched because it is still unsupported in this function.

2024-06-13 07:21 UTC, vinsentli commented
@corporateshark 
I have a question: Which time zone are you located in? ：）

2024-06-15 04:18 UTC, corporateshark commented
> @corporateshark I have a question: Which time zone are you located in? ：）

I'm typically in the PT timezone, but it can vary as the business requirements dictate. 😉

2024-06-17 02:01 UTC, closed without merging