igl | OpenGL | fix confused the difference between StencilReference and readMask
facebook/igl pull request #144
Opened 2024-07-02 11:21 UTC by vinsentli

```
void glStencilFuncSeparate(	
        GLenum face,
 	GLenum func,
 	GLint ref,
 	GLuint mask);
```
The third param is StencilReference, and the last param is mask.

https://registry.khronos.org/OpenGL-Refpages/gl4/html/glStencilFuncSeparate.xhtml

2024-07-02 19:12 UTC, mmaurer commented
It seems like we need to update one of the tests to reflect the API change in src\igl\tests\ogl\DepthStencilState.cpp, line 167: https://github.com/facebook/igl/blob/1486dcc1e0a1ca52f1f520846b751c089c7ddae1/src/igl/tests/ogl/DepthStencilState.cpp#L167

2024-07-02 19:33 UTC, corporateshark requested changes

2024-07-02 19:33 UTC, corporateshark commented on src/igl/opengl/DepthStencilState.h
> +  void bind(uint32_t frontStencilReferenceValue, uint32_t backStencilReferenceValue);
Please update tests.

2024-07-03 02:31 UTC, vinsentli commented
> It seems like we need to update one of the tests to reflect the API change in src\igl\tests\ogl\DepthStencilState.cpp, line 167:
> 
> https://github.com/facebook/igl/blob/1486dcc1e0a1ca52f1f520846b751c089c7ddae1/src/igl/tests/ogl/DepthStencilState.cpp#L167

@corporateshark done

2024-07-09 08:18 UTC, closed without merging