Emscripten WebAssembly triangle sample
facebook/igl pull request #15
Opened 2023-07-09 03:13 UTC by jwric

Some checks for emscripten were added in cmakelists files and added a sample for WebAssembly, ported from the "Tiny" triangle example.

To generate files:
```bash
$ mkdir build-em
$ cd build-em
$ cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE="<path_to_emsdk>/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake"
$ ninja
```

![image](https://github.com/facebook/igl/assets/47578360/1633a1f4-eedf-4415-ae4c-192ccdfc328b)

2023-07-09 04:21 UTC, corporateshark commented
Please apply `cmake-format`.

2023-07-09 05:01 UTC, corporateshark commented on samples/webassembly/Triangle/Triangle.cpp
> +  for (auto i = 0; i < kNumColorAttachments; ++i) {
I recommend removing this for the sake of simplicity and keeping only 1 color attachment.

2023-07-09 05:01 UTC, corporateshark approved these changes

2023-07-09 05:30 UTC, rudybear commented
Fun fact, I implemented almost identical example. I'll accept this PR and rebase my another example on top of yours.

2023-07-09 17:34 UTC, corporateshark approved these changes

2023-07-09 21:16 UTC, nlutsenko requested changes
Mostly lgtm. Stylistic, completeness and minor nits.
Please address them, and after our internal CI is done, we'll happily merge.

2023-07-09 21:16 UTC, nlutsenko commented on samples/webassembly/Triangle/Triangle.cpp
> +std::string codeVS = R"(#version 300 es
Can we use a constexpr string literal for this instead?
Say `constexpr const char*`.

We are using C++17, not 20, so this results in a global constructor.

2023-07-09 21:16 UTC, nlutsenko commented on samples/webassembly/Triangle/Triangle.cpp
> +const char* codeFS = R"(#version 300 es
Please constexpr this. :)

2023-07-09 21:16 UTC, nlutsenko commented on samples/webassembly/Triangle/Triangle.cpp
> +  device_.reset(nullptr);
Missing reset for `commandQueue_` before the device.

2023-07-09 21:16 UTC, nlutsenko commented on samples/webassembly/Triangle/Triangle.cpp
> +  device_.reset(nullptr);
Also, please use consistent style.
Either all should be ` = nullptr;` or all should be `reset(...)`

2023-07-09 21:25 UTC, corporateshark commented on samples/webassembly/Triangle/Triangle.cpp
> +      IGL_FORMAT("{}C{}", framebufferDesc.debugName.c_str(), 0).c_str());
It can be `framebufferDesc.debugName.c_str()` now and let's get rid of `IGL_FORMAT` in this file.

2023-07-10 19:15 UTC, trivedivivek commented on samples/webassembly/Triangle/Triangle.cpp
> +  Result ret;
Perhaps move these 2 lines below assertion check, and merge drawable declaration and initialization to a single line.

2023-07-10 21:16 UTC, jwric commented
I will address all of your suggested changes, and if the end changes are satisfying I suggest they should also be applied to the [Tiny.cpp](https://github.com/facebook/igl/blob/7d90f29e3542e5efa372ba18acdcd7359da4f375/samples/desktop/Tiny/Tiny.cpp) example, because I basically just copied the file and made a few edits for IGL's WebGL integration to work.

2023-07-10 22:38 UTC, corporateshark approved these changes
LGTM

2023-07-11 04:54 UTC, rudybear commented
@jwric I refactored CMakeLists a little bit, can you rebase on top of main and add Triangle.cpp into wasm folder?

2023-07-11 05:26 UTC, corporateshark commented on samples/webassembly/Triangle/Triangle.cpp
> +#if defined(__cpp_lib_format)
After `IGL_FORMAT` is removed, this entire block will no longer be required.

2023-07-11 14:44 UTC, jwric commented
> @jwric I refactored CMakeLists a little bit, can you rebase on top of main and add Triangle.cpp into wasm folder?

Done, but specifying the shell file as `"../samples/wasm/igl.html"` doesn't seem to work if you're building in a different folder.

2023-07-12 17:03 UTC, corporateshark approved these changes

2023-07-13 19:12 UTC, closed without merging