igl | opengl | Fix memory leak in RenderPipelineState::activeAttributesLocations_
facebook/igl pull request #187
Opened 2024-10-14 04:12 UTC by vinsentli

When a RenderCommandEncoder sequentially binds two IRenderPipelineStates, if both of these states have the same VertexInputState, the previous IRenderPipelineState is unable to execute unbindVertexAttributes(). As a result, the activeAttributesLocations_ of the previous RenderPipelineState remains in a continuous state of memory growth and cannot be released.

2024-10-16 00:25 UTC, EricGriffith commented
This PR fixes a memory leak, but it may cause some perf overhead if things are unbound and then immediately rebound. Is there a way to fix the memory leak without the perf overhead?

2024-10-16 10:18 UTC, vinsentli commented
@EricGriffith 
My solution is to save the activeAttributesLocations_ of the previous pipeline state, for the new draw call, only disable the attribute locations that are not needed. This way, the number of glEnable/glDisableVertexAttribArray calls can be reduced.

2024-11-03 01:22 UTC, vinsentli commented
@corporateshark This PR has opened for a long time ,is there any problem with it ?

2024-11-03 05:12 UTC, corporateshark commented
> This PR has opened for a long time ,is there any problem with it ?

@vinsentli Thank you for following up! We’re still conducting some internal testing. Rest assured, as long as this PR remains open, someone on the team will review it at some point.

2024-11-03 05:58 UTC, vinsentli commented
@corporateshark Thanks for your reply.

2024-11-25 17:11 UTC, corporateshark requested changes
Please rebase this on top of the latest `main` branch.

2024-11-25 17:11 UTC, corporateshark commented on src/igl/opengl/RenderCommandAdapter.cpp
> +    pipelineState->unbindPrePipelineVertexAttributes();
unbindPre**v**PipelineVertexAttributes()

2024-11-26 01:00 UTC, vinsentli commented on src/igl/opengl/RenderCommandAdapter.cpp
> +    pipelineState->unbindPrePipelineVertexAttributes();
done

2024-11-26 01:01 UTC, vinsentli commented
> Please rebase this on top of the latest `main` branch.

done

2024-11-26 01:13 UTC, corporateshark approved these changes

2024-11-27 23:08 UTC, closed without merging