【igl nanovg part-4】android : add nanovg resouces(image, font) to android project.
facebook/igl pull request #219
Opened 2024-11-27 11:29 UTC by vinsentli

2024-11-27 19:31 UTC, corporateshark requested changes
This step can only be done after the third-party library has been downloaded. Please submit a separate PR to update the `bootstrap-deps.json` file.

2024-11-28 01:18 UTC, vinsentli commented
> This step can only be done after the third-party library has been downloaded. Please submit a separate PR to update the `bootstrap-deps.json` file.

done

2024-11-29 21:00 UTC, corporateshark commented on build/android/app/build.gradle
> +        main.assets.srcDirs += ['../../../shell/resources/images', '../../../third-party/deps/src/nanovg/example/images', '../../../third-party/deps/src/nanovg/example' ]
How to make this configurable on the per-app basis?

2024-11-29 22:39 UTC, vinsentli commented on build/android/app/build.gradle
> +        main.assets.srcDirs += ['../../../shell/resources/images', '../../../third-party/deps/src/nanovg/example/images', '../../../third-party/deps/src/nanovg/example' ]
I don't get it.
Does per app mean which apps?

2024-12-22 13:20 UTC, closed without merging