【igl nanovg part-3】Add NanovgSession Sample
facebook/igl pull request #225
Opened 2024-12-04 14:44 UTC by vinsentli

2024-12-04 20:20 UTC, corporateshark requested changes

2024-12-04 20:20 UTC, corporateshark commented on shell/renderSessions/NanovgSession.cpp
> +  renderPass_.colorAttachments.resize(1);
Can you use C++20 designated initializers syntax here?

2024-12-04 20:20 UTC, corporateshark commented on shell/renderSessions/NanovgSession.cpp
> +double getMilliSeconds() {
Use `RenderSession::getDeltaSeconds()` instead. Or `RenderSession::getSeconds()`, if you really have to compute deltas yourself.

2024-12-04 20:20 UTC, corporateshark commented on shell/renderSessions/NanovgSession.cpp
> +  int blowup = 0;
Why a variable? Can you use `0` directly as a parameter to `renderDemo()`?

2024-12-05 02:13 UTC, vinsentli commented
done

2024-12-18 04:28 UTC, corporateshark requested changes

2024-12-18 04:28 UTC, corporateshark commented on shell/renderSessions/NanovgSession.cpp
> +  if (vg == NULL) {
```
if (!IGL_DEBUG_VERIFY(vg)) {
  return -1;
}
````

2024-12-18 04:28 UTC, corporateshark commented on shell/renderSessions/NanovgSession.cpp
> +  if (data->fontIcons == -1) {
```
if (!IGL_DEBUG_VERIFY(data->fontIcons != -1, "Could not add font icons.")) {
  return -1;
}
````

And others.

2024-12-18 06:21 UTC, vinsentli commented on shell/renderSessions/NanovgSession.cpp
> +  if (vg == NULL) {
done

2024-12-18 06:21 UTC, vinsentli commented on shell/renderSessions/NanovgSession.cpp
> +  if (data->fontIcons == -1) {
done

2025-01-09 22:57 UTC, corporateshark commented
https://github.com/facebook/igl/pull/217#issuecomment-2581404423

2025-01-09 22:57 UTC, closed without merging