[igl][IGLU] Some improvements to imgui and simple_renderer modules
facebook/igl pull request #77
Opened 2024-02-25 02:02 UTC by tgoulart

1. Expose the render command encoder in `simple_renderer::ForwardRenderPass`
2. `Session::beginFrame()` takes a concrete framebuffer instead of a descriptor
3. `simple_renderer` and `imgui` now work as expected when a stencil attachment exists

2024-02-25 02:12 UTC, corporateshark requested changes
CI is broken https://github.com/facebook/igl/actions/runs/8034808216

2024-02-25 02:39 UTC, tgoulart commented
> CI is broken https://github.com/facebook/igl/actions/runs/8034808216

Oops. Should be fixed now, I'll keep an eye on the CI results.

2024-02-25 05:19 UTC, corporateshark approved these changes

2024-02-26 07:35 UTC, corporateshark commented
@tgoulart a lot of internal tests are still broken.

2024-02-28 08:07 UTC, tgoulart commented
Dropped the diff that caused the internal breakages. One more round of testing!

2024-02-28 21:41 UTC, closed without merging